services:
  - type: web
    name: hashout-jira-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

  - type: static
    name: hashout-jira-portal
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://hashout-jira-backend.onrender.com/api
